spin_version = "1"
authors = ["{{authors}}"]
description = "{{project-description}}"
name = "{{project-name}}"
version = "1.0.0"
trigger = { type = "http", base = "{{http-base}}" }

[[component]]
id = "{{project-name | kebab_case}}"
source = "bin/Release/net7.0/{{project-name}}.wasm"
[component.build]
command = "dotnet build -c Release"
[component.trigger]
route = "/..."
