spin_manifest_version = "1"
authors = ["{{authors}}"]
description = "{{project-description}}"
name = "{{project-name}}"
version = "1.0.0"
trigger = { type = "http", base = "{{http-base}}" }

[[component]]
id = "{{project-name | snake_case}}"
source = "bin/Release/net7.0/{{project-name | dotted_pascal_case}}.wasm"
[component.build]
command = "dotnet build -c Release"
[component.trigger]
route = "{{http-path}}"
