spin_manifest_version = 2

[application]
authors = ["{{authors}}"]
description = "{{project-description}}"
name = "{{project-name}}"
version = "1.0.0"

[[trigger.http]]
route = "{{http-path}}"
component = "{{project-name | kebab_case}}"

[component.{{project-name | kebab_case}}]
source = "bin/Release/net8.0/{{project-name | dotted_pascal_case}}.wasm"
[component.{{project-name | kebab_case}}.build]
command = "dotnet build -c Release"
