#include <stdlib.h>

#include <mono-wasi/driver.h>

// These are generated by the WASI SDK during build
const char* dotnet_wasi_getentrypointassemblyname();
const char* dotnet_wasi_getbundledfile(const char* name, int* out_length);
void dotnet_wasi_registerbundledassemblies();

void spin_attach_internal_calls()
{
    // Not used yet: will be needed for host components
    // mono_add_internal_call("Fermyon.Spin.Sdk::SomeMethod", __wasm_import_something);
}
