#include <stdlib.h>
#include <string.h>
#include <sys/time.h>

#include "./spin-http.h"

#include <mono-wasi/driver.h>
#include <mono/metadata/assembly.h>
#include <mono/metadata/class.h>
#include <mono/metadata/appdomain.h>
#include <mono/metadata/image.h>
#include <mono/metadata/metadata.h>
#include <mono/metadata/object.h>
#include <mono/metadata/debug-helpers.h>
#include <mono/metadata/reflection.h>
#include <mono/utils/mono-publib.h>

#include "./host-components.h"
#include "./util.h"

// These are generated by the WASI SDK during build
const char* dotnet_wasi_getentrypointassemblyname();
const char* dotnet_wasi_getbundledfile(const char* name, int* out_length);
void dotnet_wasi_registerbundledassemblies();

MonoObject* call_clr_request_handler(MonoMethod* handler, spin_http_request_t* req, MonoObject** exn) {
    *exn = NULL;

    void *params[1];
    params[0] = req;
    return mono_wasm_invoke_method(handler, NULL, params, exn);
}

spin_http_response_t internal_error(const char* message) {
    spin_http_response_t response;
    response.status = 500;
    response.headers.is_some = false;
    response.body.is_some = true;
    response.body.val.ptr = (uint8_t*)message;
    response.body.val.len = strlen(message);
    return response;
}

unsigned long time_microseconds() {
    struct timeval tv;
    gettimeofday(&tv, NULL);
    return 1000000 * tv.tv_sec + tv.tv_usec;
}

// This is a C runtime internal: calling it is a bit of a desperate kludge.
//
// The call to __wasm_call_ctors is needed to set up the Wasm end of the preopened directories
// (and environment variables? TBC). It's normally emitted by the compiler as part of C runtime startup.
// But at the moment it is emitted only at the main() entry point. It's not clear how to get it
// emitted for component model entry points. `-Wl,--no-entry -mexec-model=reactor` might do it
// according to https://github.com/WebAssembly/wasi-sdk/issues/110; we should test this and, if it
// works, discuss ways to get it incorporated as a build option for the .NET WASI SDK.
void __wasm_call_ctors();

// If wizer is run on this module, these fields will be populated at build time and hence we'll be able
// to skip loading and initializing the runtime on a per-request basis. But if wizer isn't run, we'll
// set up the runtime separately for each request.

const char* initialization_error;
MonoMethod* http_handler;
MonoObject* http_handler_attr;
int preinitialized;

void process_http_request(spin_http_request_t *req, spin_http_response_t *ret0) {
    MonoObject* exn;
    unsigned long start_time = time_microseconds();
    MonoObject* call_result = call_clr_request_handler(http_handler, req, &exn);
    unsigned long end_time = time_microseconds();
    
    if (exn) {
        MonoString* exn_str = mono_object_to_string(exn, NULL);
        char* exn_cstr = mono_wasm_string_get_utf8(exn_str);
        *ret0 = internal_error(exn_cstr);
        return;
    }

    spin_http_response_t* resp = mono_object_unbox(call_result);

    // Add an HTTP response header giving the timing information
    // This is for debugging only - should be removed for production use
    spin_http_string_t end_time_header_str;
    spin_http_string_dup(&end_time_header_str, "time-in-dotnet");
    char* end_time_string;
    int end_time_string_len = asprintf(&end_time_string, "%f ms", (end_time - start_time) / 1000.0);
    int num_headers = ++resp->headers.val.len;
    resp->headers.val.ptr = resp->headers.is_some
        ? realloc(resp->headers.val.ptr, num_headers * sizeof(spin_http_tuple2_string_string_t))
        : malloc(num_headers * sizeof(spin_http_tuple2_string_string_t));
    resp->headers.is_some = 1;
    resp->headers.val.ptr[num_headers - 1] = (spin_http_tuple2_string_string_t){
        end_time_header_str,
        {end_time_string, end_time_string_len}
    };

    *ret0 = *resp;
}

void initialize() {
    dotnet_wasi_registerbundledassemblies();
    mono_wasm_load_runtime("", 0);
    spin_attach_internal_calls();

    entry_points_err_t entry_points_err = find_entry_points("Fermyon.Spin.Sdk.HttpHandlerAttribute", &http_handler_attr, &http_handler);
    if (entry_points_err) {
        if (entry_points_err == EP_ERR_NO_HANDLER_METHOD) {
            initialization_error = "Assembly does not contain a method with HttpHandlerAttribute";
        } else {
            initialization_error = "Internal error loading HTTP handler";
        }
        return;
    }
}

__attribute__((export_name("wizer.initialize")))
void preinitialize() {
    preinitialized = 1;
    initialize();

    // To warm the interpreter, we need to run the main code path that is going to execute per-request. That way the preinitialized
    // binary is already ready to go at full speed.

    char* warmup_url = "/warmupz";
    if (http_handler_attr) {
        MonoString* warmup_str;
        if (get_property(http_handler_attr, "WarmupUrl", (MonoObject**)&warmup_str) == GET_MEMBER_ERR_OK) {
            warmup_url = mono_wasm_string_get_utf8(warmup_str);
        }
    }

    spin_http_request_t fake_req = {
        .method = SPIN_HTTP_METHOD_GET,
        .uri = { warmup_url, strlen(warmup_url) },
        .headers = {.len = 1, .ptr = (spin_http_tuple2_string_string_t[]){{
            {"key", 3}, {"val", 3}
        }}},
        .body = { .is_some = 1, .val = { (void*)"Hello", 5 } }
    };
    spin_http_response_t fake_res;
    process_http_request(&fake_req, &fake_res);
}

void spin_http_handle_http_request(spin_http_request_t *req, spin_http_response_t *ret0) {
    __wasm_call_ctors();

    if (!preinitialized) {
        initialize();
    }
    if (initialization_error) {
        *ret0 = internal_error(initialization_error);
        return;
    }

    process_http_request(req, ret0);
}
