spin_manifest_version = 2

[application]
name = "dotnet-hello"
version = "1.0.0"

[variables.defaulted]
default = "test value"

[variables.required]
required = true

[[trigger.http]]
route = "/..."
component = "hello"

[component.hello]
source = "bin/Release/net7.0/HelloWorld.Spin.wasm"
# allow outbound http requests to this same app
allowed_http_hosts = ["127.0.0.1:3000"]
# allow outbound requests to postgres and redis
allowed_outbound_hosts = ["127.0.0.1:5432", "127.0.0.1:6379"]
files = [{ source = "assets", destination = "/assets" }]
[component.hello.variables]
defaulted = "{{ defaulted }}"
required = "{{ required }}"
[component.hello.build]
command = "dotnet build -c Release"
