spin_manifest_version = "1"
authors = ["itowlson <ivan.towlson@fermyon.com>"]
description = "Where pets store their toys!"
name = "Fermyon.PetStore"
version = "1.0.0"
trigger = { type = "http", base = "/" }

[variables]
pg_conn_str = { required = true }

[[component]]
id = "home"
source = "Fermyon.PetStore.Home/bin/Release/net7.0/Fermyon.PetStore.Home.wasm"
files = [{ source = "Fermyon.PetStore.Home/assets", destination = "/assets" }]
[component.build]
command = "dotnet build -c Release"
workdir = "Fermyon.PetStore.Home"
[component.trigger]
route = "/"

[[component]]
id = "pets"
source = "Fermyon.PetStore.Pets/bin/Release/net7.0/Fermyon.PetStore.Pets.wasm"
files = [{ source = "Fermyon.PetStore.Pets/assets", destination = "/assets" }]
[component.config]
pg_conn_str = "{{ pg_conn_str }}"
[component.build]
command = "dotnet build -c Release"
workdir = "Fermyon.PetStore.Pets"
[component.trigger]
route = "/pets"

[[component]]
id = "new_pet"
source = "Fermyon.PetStore.NewPet/bin/Release/net7.0/Fermyon.PetStore.NewPet.wasm"
files = [{ source = "Fermyon.PetStore.NewPet/assets", destination = "/assets" }]
[component.config]
pg_conn_str = "{{ pg_conn_str }}"
[component.build]
command = "dotnet build -c Release"
workdir = "Fermyon.PetStore.NewPet"
[component.trigger]
route = "/pets/new"

[[component]]
id = "pet"
source = "Fermyon.PetStore.Pet/bin/Release/net7.0/Fermyon.PetStore.Pet.wasm"
files = [{ source = "Fermyon.PetStore.Pet/assets", destination = "/assets" }]
[component.config]
pg_conn_str = "{{ pg_conn_str }}"
[component.build]
command = "dotnet build -c Release"
workdir = "Fermyon.PetStore.Pet"
[component.trigger]
route = "/pet/..."

[[component]]
id = "toys"
source = "Fermyon.PetStore.Toys/bin/Release/net7.0/Fermyon.PetStore.Toys.wasm"
files = [{ source = "Fermyon.PetStore.Toys/assets", destination = "/assets" }]
[component.config]
pg_conn_str = "{{ pg_conn_str }}"
[component.build]
command = "dotnet build -c Release"
workdir = "Fermyon.PetStore.Toys"
[component.trigger]
route = "/toys"

[[component]]
id = "new_toy"
source = "Fermyon.PetStore.NewToy/bin/Release/net7.0/Fermyon.PetStore.NewToy.wasm"
files = [{ source = "Fermyon.PetStore.NewToy/assets", destination = "/assets" }]
[component.config]
pg_conn_str = "{{ pg_conn_str }}"
[component.build]
command = "dotnet build -c Release"
workdir = "Fermyon.PetStore.NewToy"
[component.trigger]
route = "/toys/new"

[[component]]
id = "toy"
source = "Fermyon.PetStore.Toy/bin/Release/net7.0/Fermyon.PetStore.Toy.wasm"
files = [{ source = "Fermyon.PetStore.Toy/assets", destination = "/assets" }]
[component.config]
pg_conn_str = "{{ pg_conn_str }}"
[component.build]
command = "dotnet build -c Release"
workdir = "Fermyon.PetStore.Toy"
[component.trigger]
route = "/toy/..."
