spin_manifest_version = 2

[application]
authors = ["itowlson <ivan.towlson@fermyon.com>"]
description = "Where pets store their toys!"
name = "Fermyon.PetStore"
version = "1.0.0"

[variables.pg_conn_str]
required = true

[[trigger.http]]
route = "/"
component = "home"

[component.home]
source = "Fermyon.PetStore.Home/bin/Release/net8.0/Fermyon.PetStore.Home.wasm"
files = [{ source = "Fermyon.PetStore.Home/assets", destination = "/assets" }]
allowed_outbound_hosts = ["http://localhost:3000", "postgres://localhost:5432"]
[component.home.build]
command = "dotnet build -c Release"
workdir = "Fermyon.PetStore.Home"

[[trigger.http]]
route = "/pets"
component = "pets"

[component.pets]
source = "Fermyon.PetStore.Pets/bin/Release/net8.0/Fermyon.PetStore.Pets.wasm"
files = [{ source = "Fermyon.PetStore.Pets/assets", destination = "/assets" }]
allowed_outbound_hosts = ["http://localhost:3000", "postgres://localhost:5432"]
[component.pets.variables]
pg_conn_str = "{{ pg_conn_str }}"
[component.pets.build]
command = "dotnet build -c Release"
workdir = "Fermyon.PetStore.Pets"

[[trigger.http]]
route = "/pets/new"
component = "new-pet"

[component.new-pet]
source = "Fermyon.PetStore.NewPet/bin/Release/net8.0/Fermyon.PetStore.NewPet.wasm"
files = [{ source = "Fermyon.PetStore.NewPet/assets", destination = "/assets" }]
allowed_outbound_hosts = ["http://localhost:3000", "postgres://localhost:5432"]
[component.new-pet.variables]
pg_conn_str = "{{ pg_conn_str }}"
[component.new-pet.build]
command = "dotnet build -c Release"
workdir = "Fermyon.PetStore.NewPet"

[[trigger.http]]
route = "/pet/..."
component = "pet"

[component.pet]
source = "Fermyon.PetStore.Pet/bin/Release/net8.0/Fermyon.PetStore.Pet.wasm"
files = [{ source = "Fermyon.PetStore.Pet/assets", destination = "/assets" }]
allowed_outbound_hosts = ["http://localhost:3000", "postgres://localhost:5432"]
[component.pet.variables]
pg_conn_str = "{{ pg_conn_str }}"
[component.pet.build]
command = "dotnet build -c Release"
workdir = "Fermyon.PetStore.Pet"

[[trigger.http]]
route = "/toys"
component = "toys"

[component.toys]
source = "Fermyon.PetStore.Toys/bin/Release/net8.0/Fermyon.PetStore.Toys.wasm"
files = [{ source = "Fermyon.PetStore.Toys/assets", destination = "/assets" }]
allowed_outbound_hosts = ["http://localhost:3000", "postgres://localhost:5432"]
[component.toys.variables]
pg_conn_str = "{{ pg_conn_str }}"
[component.toys.build]
command = "dotnet build -c Release"
workdir = "Fermyon.PetStore.Toys"

[[trigger.http]]
route = "/toys/new"
component = "new-toy"

[component.new-toy]
source = "Fermyon.PetStore.NewToy/bin/Release/net8.0/Fermyon.PetStore.NewToy.wasm"
files = [{ source = "Fermyon.PetStore.NewToy/assets", destination = "/assets" }]
allowed_outbound_hosts = ["http://localhost:3000", "postgres://localhost:5432"]
[component.new-toy.variables]
pg_conn_str = "{{ pg_conn_str }}"
[component.new-toy.build]
command = "dotnet build -c Release"
workdir = "Fermyon.PetStore.NewToy"

[[trigger.http]]
route = "/toy/..."
component = "toy"

[component.toy]
source = "Fermyon.PetStore.Toy/bin/Release/net8.0/Fermyon.PetStore.Toy.wasm"
files = [{ source = "Fermyon.PetStore.Toy/assets", destination = "/assets" }]
allowed_outbound_hosts = ["http://localhost:3000", "postgres://localhost:5432"]
[component.toy.variables]
pg_conn_str = "{{ pg_conn_str }}"
[component.toy.build]
command = "dotnet build -c Release"
workdir = "Fermyon.PetStore.Toy"
